import createDater from "../src/createDater"


describe("dater format", () => {
    it("test 1695019785071", () => {
        const dater = createDater(new Date(1695019785071))
        expect(dater.format("")).toBe("")
        expect(dater.format("YYYY")).toBe("2023")
        expect(dater.format("YY")).toBe("23")
        expect(dater.format("MMMM")).toBe("September")
        expect(dater.format("MMM")).toBe("Sep")
        expect(dater.format("MM")).toBe("09")
        expect(dater.format("M")).toBe("9")
        expect(dater.format("DD")).toBe("18")
        expect(dater.format("D")).toBe("18")
        expect(dater.format("ddd")).toBe("Monday")
        expect(dater.format("dd")).toBe("Mon")
        expect(dater.format("d")).toBe("1")
        expect(dater.format("HH")).toBe("14")
        expect(dater.format("H")).toBe("14")
        expect(dater.format("hh")).toBe("02")
        expect(dater.format("h")).toBe("2")
        expect(dater.format("mm")).toBe("49")
        expect(dater.format("m")).toBe("49")
        expect(dater.format("SSS")).toBe("071")
        expect(dater.format("ss")).toBe("45")
        expect(dater.format("s")).toBe("45")
        expect(dater.format("A")).toBe("PM")
        expect(dater.format("a")).toBe("pm")
        expect(dater.format("ZZ")).toBe("+0800")
        expect(dater.format("Z")).toBe("+08:00")
        expect(dater.format("YYYY-MM-DD")).toBe("2023-09-18")
        expect(dater.format("HH:mm:ss:SSS")).toBe("14:49:45:071")
    })
    it("test 0", () => {
        const dater = createDater(new Date(0))
        expect(dater.format("")).toBe("")
        expect(dater.format("YYYY")).toBe("1970")
        expect(dater.format("YY")).toBe("70")
        expect(dater.format("MMMM")).toBe("January")
        expect(dater.format("MMM")).toBe("Jan")
        expect(dater.format("MM")).toBe("01")
        expect(dater.format("M")).toBe("1")
        expect(dater.format("DD")).toBe("01")
        expect(dater.format("D")).toBe("1")
        expect(dater.format("ddd")).toBe("Thursday")
        expect(dater.format("dd")).toBe("Thu")
        expect(dater.format("d")).toBe("4")
        expect(dater.format("HH")).toBe("08")
        expect(dater.format("H")).toBe("8")
        expect(dater.format("hh")).toBe("08")
        expect(dater.format("h")).toBe("8")
        expect(dater.format("mm")).toBe("00")
        expect(dater.format("m")).toBe("0")
        expect(dater.format("SSS")).toBe("000")
        expect(dater.format("ss")).toBe("00")
        expect(dater.format("s")).toBe("0")
        expect(dater.format("A")).toBe("AM")
        expect(dater.format("a")).toBe("am")
        expect(dater.format("ZZ")).toBe("+0800")
        expect(dater.format("Z")).toBe("+08:00")
        expect(dater.format("YYYY-MM-DD")).toBe("1970-01-01")
        expect(dater.format("HH:mm:ss:SSS")).toBe("08:00:00:000")
    })
})