import provider from "../src/daterProvider"

describe("make dater", () => {
    it("test 1695019785071", () => {
        const dater = provider(new Date(1695019785071))
        expect(dater.YYYY).toBe("2023")
        expect(dater.YY).toBe("23")
        expect(dater.MMMM).toBe("September")
        expect(dater.MMM).toBe("Sep")
        expect(dater.MM).toBe("09")
        expect(dater.M).toBe("9")
        expect(dater.DD).toBe("18")
        expect(dater.D).toBe("18")
        expect(dater.ddd).toBe("Monday")
        expect(dater.dd).toBe("Mon")
        expect(dater.d).toBe("1")
        expect(dater.HH).toBe("14")
        expect(dater.H).toBe("14")
        expect(dater.hh).toBe("02")
        expect(dater.h).toBe("2")
        expect(dater.mm).toBe("49")
        expect(dater.m).toBe("49")
        expect(dater.SSS).toBe("071")
        expect(dater.ss).toBe("45")
        expect(dater.s).toBe("45")
        expect(dater.A).toBe("PM")
        expect(dater.a).toBe("pm")
        expect(dater.ZZ).toBe("+0800")
        expect(dater.Z).toBe("+08:00")
    })
    it("test 0", () => {
        const dater = provider(new Date(0))
        expect(dater.YYYY).toBe("1970")
        expect(dater.YY).toBe("70")
        expect(dater.MMMM).toBe("January")
        expect(dater.MMM).toBe("Jan")
        expect(dater.MM).toBe("01")
        expect(dater.M).toBe("1")
        expect(dater.DD).toBe("01")
        expect(dater.D).toBe("1")
        expect(dater.ddd).toBe("Thursday")
        expect(dater.dd).toBe("Thu")
        expect(dater.d).toBe("4")
        expect(dater.HH).toBe("08")
        expect(dater.H).toBe("8")
        expect(dater.hh).toBe("08")
        expect(dater.h).toBe("8")
        expect(dater.mm).toBe("00")
        expect(dater.m).toBe("0")
        expect(dater.SSS).toBe("000")
        expect(dater.ss).toBe("00")
        expect(dater.s).toBe("0")
        expect(dater.A).toBe("AM")
        expect(dater.a).toBe("am")
        expect(dater.ZZ).toBe("+0800")
        expect(dater.Z).toBe("+08:00")
    })
})